Marekhorst 1475 rewrite citation matching algorithm in spark 2.4
openaire/iis pull request #1482
Opened 2024-10-16 10:50 UTC by marekhorst

This PR includes all the changes required to rewrite citationmatching code from spark 1.6 to spark 2.4 (and from scala 2.10 to scala 2.11).

I decided to introduce a new `iis-3rdparty-coansys-citation-matching` module encapsulating the whole code moved from CoAnSys (see `README.markdown` file for details) and adjusted to spark2.4/scala2.11 while having `iis-wf-citationmatching` updated in just 3-4 places in the java code (mostly related to `Iterator`s) and having `pom.xml` dependencies updated.

This pull request includes several WiP commits, most of them are bound to #1475 but one of them is related to #1481 (introduction of two spark timeout related properties). Once I get to the point of merging with the master branch I will either squash those commits to the one with referencing two issues in the commit message or split into two separate commits.

2024-10-16 11:00 UTC, marekhorst commented
I found this useful hint (`Alt + click` on any chevron icon in the file’s header):
https://dzhavat.github.io/2021/11/08/quick-way-to-collapse-expand-all-files-at-once-on-a-pull-request-on-github.html
while dealing with such a great number of changed files e.g. to focus only on a subset of changes related to CoAnSys or IIS codebase.

2024-10-17 10:38 UTC, mpol requested changes
Everything looks OK regarding the code, but the new README needs some fixes.

2024-10-17 10:38 UTC, mpol commented on iis-3rdparty-coansys-citation-matching/README.markdown
> +https://github.com/CeON/CoAnSys/tree/master/citation-matching/citation-matching-coansys-code
It is actually from `citation-matching-core-code`

2024-10-17 10:38 UTC, mpol commented on iis-3rdparty-coansys-citation-matching/README.markdown
> +https://github.com/CeON/CoAnSys/tree/master/ceon-scala-commons-lite
I think we should document the exact commit `f0373f0416c93d3cff3a6ea137da09fba1481cad` from which the files were copied.

2024-10-17 10:57 UTC, marekhorst commented
@mpol I have just refined the `README.markdown` file content a little bit.

2024-10-17 11:08 UTC, mpol approved these changes
LGTM

2024-10-17 11:21 UTC, marekhorst commented
Changes covered with this PR were merged with this commit:

38d5290ae84ca732b786ce49fc16db7d99367bb3

after rebasing and squashing all the commits into the one.

2024-10-17 11:21 UTC, closed without merging